# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='update',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
